# Generated by Django 4.2.23 on 2025-06-30 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_user_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="FirstName",
            new_name="firstName",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="LastName",
            new_name="lastName",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phonenumber",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_varified",
            field=models.BooleanField(default=False),
        ),
    ]
