# Generated by Django 4.2.23 on 2025-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_firstname_user_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_expire",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
